services:
  nextcloud:
    image: kefaslungu/hng-nextcloud
    volumes:
      - nextcloud_data:/var/www/html
      - HNG-nginx-logs:/var/log/nginx:ro

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - HNG-nginx-logs:/var/log/nginx
    depends_on:
      - nextcloud

  detector:
    build:
      context: ./detector
    environment:
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    volumes:
      - ./detector:/app
      - HNG-nginx-logs:/var/log/nginx:ro
    working_dir: /app
    command: python3 -u main.py
    ports:
      - "8081:8081"
    cap_add:
      - NET_ADMIN
    depends_on:
      - nginx

volumes:
  nextcloud_data:
  HNG-nginx-logs:
