log_format json_combined escape=json
'{ "source_ip": "$remote_addr", '
'"timestamp": "$time_iso8601", '
'"method": "$request_method", '
'"path": "$request_uri", '
'"status": "$status", '
'"response_size": "$body_bytes_sent" }';

access_log /var/log/nginx/hng-access.log json_combined;

# HTTP - Redirect dashboard to HTTPS
server {
    listen 80;
    server_name ${DASHBOARD_DOMAIN};
    return 301 https://$server_name$request_uri;
}

# HTTPS - Dashboard
server {
    listen 443 ssl;
    server_name ${DASHBOARD_DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DASHBOARD_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DASHBOARD_DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://host.docker.internal:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# HTTP - Nextcloud (IP only, no SSL)
server {
    listen 80 default_server;
    server_name _;

    location / {
        proxy_pass http://nextcloud:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
